A=json.loads((ROOT/'content/articles.json').read_text())
BY={p['slug']:p for p in PAPERS}
def paragraphs(xs): return ''.join('<p>'+e(x)+'</p>' for x in xs)
def svgframe(label): return f'<svg viewBox="0 0 620 300" role="img" aria-label="{e(label)}"><g data-plot></g></svg>'
def demo(p):
 t=p['type'];s=p['slug']
 if t=='surf':
  return '<div class="demo" data-demo="surf"><h3>Try equal weights and equal distances</h3><p class="note">Exact scalarization of the toy objectives f₁(z) = z² and f₂(z) = (1 − z)⁴ for 0 ≤ z ≤ 1. Both objectives are minimized. The green points invert a numerically constructed arc-length map.</p><div class="demo-controls"><label for="sample-count">Number of solutions</label><input id="sample-count" type="range" min="4" max="24" value="10"><output for="sample-count" data-count>10</output></div>'+svgframe('Toy Pareto front comparing equal-weight and equal-arc-length points')+'<div class="legend"><span>Uniform weights</span><span>Uniform arc length</span></div><p class="metric" data-metric aria-live="polite"></p><p class="note">Gap CV is the standard deviation of adjacent arc-length gaps divided by their mean. Lower is more even. This calculated toy example illustrates geometry; it is not the paper’s experimental data or a run of its iterative SURF algorithm.</p></div>'
 if t=='constraint':
  return '<div class="demo" data-demo="constraint"><h3>Move the follower’s feasible boundary</h3><p>Minimize (y − 2x)² over 0 ≤ y ≤ x.</p><div class="demo-controls"><label for="outer-x">Outer decision x</label><input id="outer-x" type="range" min="0" max="3" step="0.05" value="1"><output for="outer-x" data-count>1.00</output></div>'+svgframe('Toy lower-level quadratic objective with a moving feasibility bound')+'<p class="metric" data-metric aria-live="polite"></p><p class="note">The unconstrained minimizer is 2x. For x ≥ 0, the feasible minimizer is y* = x. This is an exact toy lower-level solve, not an implementation of BLOCC.</p></div>'
 if t=='timing':
  return '<div class="demo" data-demo="timing"><h3>Same exposure, different timing</h3><p>Toggle whether a toy agent is long or flat before each interval. Returns are fixed at −20, +15, −10, +25, −15, and +5 basis points.</p><div class="toy-actions">'+''.join(f'<button type="button" data-action="{i}" aria-pressed="{str(i%2==0).lower()}">Interval {i+1}: {"Long" if i%2==0 else "Flat"}</button>' for i in range(6))+'</div><div class="demo-controls"><button class="button" type="button" data-invert>Invert schedule</button><button class="button" type="button" data-reset>Reset</button></div>'+svgframe('Synthetic interval returns and a selected binary exposure schedule')+'<p class="metric" data-metric aria-live="polite"></p><p class="note">Computed using the paper’s timing formula on six synthetic returns. This is not a trading simulation or empirical RetailAgent result. Inverting a schedule negates its centered timing score.</p></div>'
 if t=='speech':
  return '<div class="demo" data-demo="speech"><h3>Follow the two target sources</h3><div class="demo-controls"><button class="button primary" type="button" data-source="anchor" aria-pressed="true">Raw-input anchor</button><button class="button" type="button" data-source="enhanced" aria-pressed="false">Enhanced target</button></div><div class="diagram-flow"><div class="flow-node" data-node="input">Audio features<small>Observed input</small></div><span class="flow-separator" aria-hidden="true">›</span><div class="flow-node" data-node="repr">Intermediate features<small>Inside the speech model</small></div><span class="flow-separator" aria-hidden="true">›</span><div class="flow-node" data-node="quant">Random quantizer<small>Discrete pseudo-labels</small></div></div><p data-explanation aria-live="polite"></p><p class="note">Schematic target-source inspection. The buttons select which branch to explain; they do not change a training parameter.</p><h3>Measured downstream WER</h3>'+svgframe('Reported LibriSpeech word error rates for BEST-RQ and BiRQ')+'<div class="legend"><span>BEST-RQ</span><span>BiRQ</span></div><p class="note">Source: Table 2. 155M Conformer, 960h LibriSpeech SSL pretraining, 100h labeled fine-tuning. Lower WER is better.</p></div>'
 if t=='curvature':
  return '<div class="demo" data-demo="curvature"><h3>Joint curvature and reduced curvature</h3><p>Take Hγ(x, y) = x²/2 + γ(y − x)². Minimizing over y gives Fγ(x) = x²/2.</p><div class="demo-controls"><label for="penalty">Penalty γ</label><input id="penalty" type="range" min="1" max="30" value="5"><output for="penalty" data-count>5</output></div>'+svgframe('Toy joint-objective slice and penalty-independent reduced objective')+'<div class="legend"><span>Fixed slice Hγ(x, 0)</span><span>Reduced Fγ(x)</span></div><p class="metric" data-metric aria-live="polite"></p><p class="note">The fixed slice has curvature 1 + 2γ, while the reduced objective has curvature 1. This exact quadratic example illustrates the difference between objectives; it is not the theorem proof or measured convergence data.</p></div>'
 return '<div class="demo" data-demo="schedule"><h3>Inspect the update schedule</h3><div class="demo-controls"><button class="button primary" type="button" data-mode="single" aria-pressed="true">Single-loop illustration</button><button class="button" type="button" data-mode="nested" aria-pressed="false">Nested-loop illustration</button><button class="button" type="button" data-next>Next update</button></div><div class="diagram-flow"><div class="flow-node" data-stage="lower">Lower-level update<small data-lower>0 updates</small></div><span class="flow-separator" aria-hidden="true">›</span><div class="flow-node" data-stage="upper">Upper-level update<small data-upper>0 updates</small></div></div><p data-explanation aria-live="polite"></p><p class="note">The nested schedule uses four illustrative inner updates per outer step. The single-loop schedule uses one. These counts explain the layout of a loop and are not algorithm settings or runtime measurements from the paper. Coupled-constraint PBGD-Free retains an inner loop.</p></div>'
base_demo=demo
def demo(p):
 if p['slug']=='efficient-penalty':
  return '<div class="demo" data-demo="regime"><div class="eyebrow">Method structure</div><h3>Does the lower-level feasible set move?</h3><p>Select the constraint regime to inspect the PBGD-Free loop structure analyzed in the broader preprint.</p><div class="demo-controls"><button class="button primary" type="button" data-regime="fixed" aria-pressed="true">Fixed feasible set</button><button class="button" type="button" data-regime="coupled" aria-pressed="false">Coupled constraints</button></div><div class="equation" data-regime-formula>Y(x) = Ỹ</div><div class="regime-result"><strong data-regime-title>Uncoupled constraints</strong><p data-regime-description aria-live="polite"></p></div><p class="note">A schematic of the analyzed methods in Sections 4–5. Selecting a regime does not solve a bilevel problem or estimate its runtime.</p></div>'
 if p['slug']=='pbgd-free':
  return '<div class="demo" data-demo="flatness"><div class="eyebrow">Definition 1 / illustrative envelope</div><h3>How does a flatness bound shrink?</h3><p>Compare the distance contribution d with d^1.5 + 0.003, using c = 1. Here d = ‖y − y*‖. These are illustrative bound values, not measured losses.</p><div class="demo-controls"><label for="deviation">Distance from y*</label><input id="deviation" type="range" min="0" max="1" step="0.01" value="0.1"><output for="deviation" data-count>0.10</output></div>'+svgframe('Illustrative linear distance bound and flatness envelope with residual')+'<div class="legend"><span>Linear distance d</span><span>Flatness envelope d^1.5 + 0.003</span></div><div class="flatness-values"><span>Linear distance<strong data-linear></strong></span><span>Flatness envelope<strong data-flat></strong></span></div><p class="metric" data-metric aria-live="polite"></p><p class="note">The nonzero residual remains as d approaches zero. A curve drawn from assumed constants does not establish flatness for a model or certify the PBGD-Free convergence assumptions.</p></div>'
 if p['type']=='speech':
  return '<div class="demo" data-demo="speech"><div class="eyebrow">Information flow / schematic</div><h3>Follow the two target sources</h3><div class="demo-controls"><button class="button primary" type="button" data-source="anchor" aria-pressed="true">Raw-input anchor</button><button class="button" type="button" data-source="enhanced" aria-pressed="false">Enhanced target</button></div><div class="target-diagram"><div class="flow-node" data-node="input">Audio features<small>Observed input</small></div><div class="target-branches"><div class="flow-node" data-node="anchor">Raw-input quantization<small>Anchor labels</small></div><div class="flow-node" data-node="repr">Intermediate representation<small>Enhanced-label source</small></div></div><div class="flow-node" data-node="quant">Target prediction<small>Learning with both label sources</small></div></div><p data-explanation aria-live="polite"></p><p class="note">The intermediate branch includes random-projection quantization. These controls explain the design; they do not alter a training run or predict word error rate.</p></div>'
 return base_demo(p)
def bib(p):
 authors=' and '.join(p['authors']);key='jiang'+str(p['year'])+p['slug'].replace('-','')
 if p['slug']=='retailagent':key='zhang2026retailagent'
 if p['venue']=='Preprint':
  return f'@misc{{{key},\n  title = {{{p["title"]}}},\n  author = {{{authors}}},\n  year = {{{p["year"]}}},\n  eprint = {{{p["arxiv"]}}},\n  archivePrefix = {{arXiv}},\n  url = {{{p["paper"]}}}\n}}'
 return f'@inproceedings{{{key},\n  title = {{{p["title"]}}},\n  author = {{{authors}}},\n  booktitle = {{{p["venue"]}}},\n  year = {{{p["year"]}}},\n  url = {{{p["paper"]}}}\n}}'
def sourcehtml(p):
 return '<ul class="source-list">'+''.join('<li><a href="'+e(s['url'])+'">'+e(s['label'])+'</a></li>' for s in p['sources'])+'</ul>'
def videohtml(p,a):
 return ''.join(f'<div class="story-scene"><time>{e(time)}</time><div><p>{e(narration)}</p><p class="visual"><strong>On screen:</strong> {e(visual)}</p></div></div>' for time,visual,narration in a['scenes'])+f'<p><a class="button" href="../../resources/{p["slug"]}-video-script.md" download>Download narration and storyboard</a></p>'
def relatedhtml(p,a):
 return '<div class="pill-links">'+''.join(f'<a href="../{s}/">{e(BY[s]["short"])}</a>' for s in a['related'])+'</div>'
S=json.loads((ROOT/'content/project-stories.json').read_text())
def authorshtml(p):
 return ', '.join('<span class="self">'+e(n)+'</span>' if n=='Liuyuan Jiang' else e(n) for n in p['authors'])
def glance(p,t):
 s=p['slug'];inside=''
 if s=='surf':inside=chart()
 elif s=='retailagent':inside='<div class="glance-pair"><span>Intact schedule</span><strong>−45.7 bps</strong></div><div class="glance-pair"><span>Global shuffle</span><strong>−3.5 bps</strong></div><div class="glance-pair"><span>Same-day shuffle</span><strong>−8.7 bps</strong></div>'
 elif s=='birq':inside='<div class="glance-pair"><span>BEST-RQ</span><strong>19.6%</strong></div><div class="glance-pair"><span>BiRQ</span><strong>12.6%</strong></div>'
 elif s=='pbgd-free':inside='<div class="big-equation">Upper-loss variation<br>≤ c ‖y − y*‖<sup>α</sup> + δ</div><div class="glance-path"><div>Flatness<small>Controls sensitivity to the inner response</small></div><div>Simplified update<small>Removes the value-function loop</small></div></div>'
 elif s=='smoothness':inside='<div class="glance-pair"><span>Joint curvature bound</span><strong>O(γ)</strong></div><div class="glance-pair"><span>Reduced smoothness</span><strong>O(1)</strong></div><div class="big-equation">Fγ = γ (vγ − v)</div>'
 elif s=='efficient-penalty':inside='<div class="glance-path"><div>Uncoupled / Ỹ<small>Fully single-loop PBGD-Free</small></div><div>Coupled / Y(x)<small>Moving constraints; inner solve retained</small></div></div>'
 else:
  pts=' '.join(f'{45+115*y:.2f},{245-50*(y-2)**2:.2f}' for y in [i*3/100 for i in range(101)])
  inside=f'<svg viewBox="0 0 430 295" role="img" aria-label="Exact toy lower-level quadratic at x equals one, with feasible region zero to one and unconstrained minimizer two"><rect x="45" y="35" width="115" height="210" fill="#e1f2ee"/><path d="M45 35 V245 H400" stroke="#8b98af" fill="none"/><polyline points="{pts}" stroke="#354ac6" stroke-width="3" fill="none"/><path d="M160 35 V245" stroke="#007c70" stroke-dasharray="5 4"/><circle cx="160" cy="195" r="6" fill="#007c70"/><circle cx="275" cy="245" r="6" fill="#354ac6"/><text x="102" y="65" text-anchor="middle" fill="#007c70" font-size="15">Feasible</text><text x="160" y="270" text-anchor="middle" fill="#526077" font-size="15">y* = x = 1</text><text x="300" y="270" text-anchor="middle" fill="#526077" font-size="15">2x = 2</text><text x="225" y="22" text-anchor="middle" fill="#526077" font-size="15">Lower-level loss at x = 1</text></svg>'
 return '<aside class="glance" aria-label="Research at a glance"><div class="eyebrow">'+e(t['figure_title'])+'</div>'+inside+'<p>'+e(t['figure_caption'])+'</p></aside>'
def resultchart(t):
 if 'chart' not in t:return ''
 c=t['chart'];rows=''
 for label,v,display in c['rows']:
  ours=label in ['SURF','BiRQ','PBGD-Free','BLOCC']
  rows+=f'<div class="data-row{ " ours" if ours else ""}"><span>{e(label)}</span><div class="data-track" aria-hidden="true"><div class="data-bar" style="--bar:{100*v/c["max"]:.2f}%"></div></div><span class="value">{e(display)}</span></div>'
 return '<figure class="evidence-chart"><figcaption><p class="chart-heading">'+e(c['title'])+'</p><p class="chart-caption">'+e(c['caption'])+'</p></figcaption>'+rows+'</figure>'
def kicker(n,label):return f'<div class="section-kicker"><span>{n:02}</span><span>{e(label)}</span></div>'
for p in PAPERS:
 s=p['slug'];a=A[s];t=S[s]
 labels=[('takeaway','Takeaway'),('idea','Explanation'),('interactive','Explore the idea'),('evidence','Results'),('technical','A closer look'),('citation','Cite this work')]
 toc='<aside class="toc" aria-label="Page contents"><div class="eyebrow">On this page</div>'+''.join(f'<a href="#{i}"><span>{j:02}</span>{l}</a>' for j,(i,l) in enumerate(labels))+'</aside>'
 actions=f'<a class="button primary" href="{p["paper"]}">Paper</a>'
 if p.get('code'):actions+=f'<a class="button" href="{p["code"]}">Code</a>'
 actions+=f'<a class="button" href="../../videos/{s}/">Video storyboard</a>'
 method='<div class="method-path">'+''.join(f'<div class="method-step"><div class="step-number">{i:02}</div><h3>{e(title)}</h3><p>{e(body)}</p></div>' for i,(title,body) in enumerate(t['steps'],1))+'</div>'
 blocks=['<div class="story-block"><h3>'+e(title)+'</h3><p>'+e(text)+'</p></div>' for title,text in a['explanation']]
 explanation=''.join(blocks[:2])+method+''.join(blocks[2:])
 why='<div class="reading-note"><strong>'+e(t['why_title'])+'</strong><p>'+e(t['why'])+'</p></div>'
 scope='<div class="scope-box"><h3>How to read this result</h3><p>'+e(a['boundary'])+'</p></div>'
 evidence='<p class="lede">'+e(t['result_context'])+'</p>'+resultchart(t)
 if s=='smoothness':evidence+='<div class="result-grid"><div class="result-stat"><strong>O(ε⁻¹·⁵)</strong><p>Compared outer-iteration bound</p></div><div class="result-stat"><strong>O(ε⁻¹)</strong><p>Sharper bound under the stated assumptions</p></div></div>'
 if s=='efficient-penalty':evidence+='<div class="evidence"><strong>Reduced smoothness / uncoupled constraints</strong><p>Theorem 1 gives an O(1) smoothness bound for Fγ under its stated assumptions, without scaling with γ.</p></div><div class="evidence"><strong>Reduced smoothness / coupled constraints</strong><p>Theorem 4 extends the bound under Assumptions 1–5 and sufficiently large γ. The different feasible-set regularity is part of this result.</p></div>'
 evidence+='<p>'+e(t['second_result'])+'</p><p><a href="'+e(p['paper'])+'">'+e(t['result_reference'])+' in the paper</a></p>'+scope
 technical='<div class="equation">'+e(a['formula'])+'</div><p>'+e(a['formula_note'])+'</p><dl class="notation">'+''.join('<dt>'+e(symbol)+'</dt><dd>'+e(desc)+'</dd>' for symbol,desc in t['notation'])+'</dl><h3>The technical idea</h3>'+''.join('<div class="story-block"><h3>'+e(title)+'</h3><p>'+e(text)+'</p></div>' for title,text in t['reasoning'])
 if t.get('update_equations'):technical+='<h3>The single-loop update</h3>'+''.join('<div class="equation">'+e(eq)+'</div>' for eq in t['update_equations'])+'<p>'+e(t['update_caption'])+'</p>'
 technical+='<details><summary>Assumptions and guarantee</summary><p>'+e(a['formal'])+'</p><a href="'+e(p['paper'])+'">'+e(t['anchor'])+' in the paper</a></details><div class="connection"><h3>How this connects to the other papers</h3><p>'+e(t['connection'])+'</p>'+relatedhtml(p,a)+'</div>'
 venue_note=f'<p class="note">{e(p["venue_note"])}</p>' if p.get('venue_note') else ''
 body=head(p['short']+' | Liuyuan Jiang',t['deck'],2,'papers/'+s+'/')+f'<main id="main" class="wrap"><header class="project-hero"><a class="route-back" href="../../index.html#papers">All research</a><div class="project-intro"><div><div class="meta"><span class="venue">{e(p["venue"])}</span><span>{e(p["topic"])}</span></div><h1>{e(t["headline"])}</h1><p class="subtitle">{e(t["deck"])}</p></div>{glance(p,t)}</div><div class="paper-record"><div><p class="formal-title">{e(p["title"])}</p><p class="authors">{authorshtml(p)}</p>{venue_note}</div><div class="actions">{actions}</div></div></header><div class="project-layout">{toc}<article class="article"><div id="takeaway" class="takeaway"><div class="eyebrow">The takeaway</div><p>{e(a["takeaway"])}</p></div><section id="idea">{kicker(1,"Explanation")}<h2>{e(a["explanation_title"])}</h2>{explanation}{why}</section><section id="interactive">{kicker(2,"Interactive")}<h2>Explore the idea</h2>{demo(p)}</section><section id="evidence">{kicker(3,"Results")}<h2>{e(t["result_title"])}</h2>{evidence}</section><section id="technical">{kicker(4,"A closer look")}<h2>Inside the method</h2>{technical}</section><section id="citation">{kicker(5,"Reference")}<h2>Cite this work</h2><button class="button" type="button" data-copy="bibtex">Copy BibTeX</button><p class="status" role="status"></p><pre id="bibtex">{e(bib(p))}</pre><h3>Sources</h3>{sourcehtml(p)}</section></article></div></main>'+footer(2)
 save('papers/'+s+'/index.html',body)
 video=head(p['short']+' | Video storyboard', 'Narration and storyboard for '+p['title'],2,'videos/'+s+'/')+f'<main id="main" class="wrap"><article class="video-page"><a class="route-back" href="../../papers/{s}/">{e(p["short"])} project page</a><div class="video-intro"><div><p class="eyebrow" style="margin-top:30px">{e(p["short"])} / Video</p><h1>{e(t["headline"])}</h1><p class="subtitle">{e(p["title"])}</p><p class="authors">{authorshtml(p)}</p><div class="actions"><a class="button primary" href="../../papers/{s}/">Project page</a><a class="button" href="{p["paper"]}">Read the paper</a></div></div><aside class="video-meta"><p><strong>Ready to record</strong>Narration and storyboard draft</p><p><strong>~2 minutes</strong>Five scenes with diagram pauses</p><p>Recorded video will be added here when available.</p></aside></div><section aria-label="Narration and storyboard">{videohtml(p,a)}</section><section class="video-sources"><h2>Research sources</h2>{sourcehtml(p)}</section></article></main>'+footer(2)
 save('videos/'+s+'/index.html',video)
 # Preserve old incoming URLs while keeping one substantive page per paper.
 target=f'../../papers/{s}/#idea'
 canonical=ORIGIN+'/papers/'+s+'/'
 redirect='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="This explanation is integrated into the paper project page."><meta name="robots" content="noindex,follow"><title>'+e(p['short'])+' explanation</title><link rel="canonical" href="'+e(canonical)+'"><meta http-equiv="refresh" content="0; url='+e(target)+'"></head><body><main><h1>Continue to the project page</h1><p><a href="'+e(target)+'">Read the integrated explanation</a></p></main><script>location.replace('+json.dumps(target)+');</script></body></html>'
 save('blog/'+s+'/index.html',redirect)
 md='# '+a['explanation_title']+'\n\n'+a['lead']+'\n\n'+''.join('## '+title+'\n\n'+text+'\n\n' for title,text in a['explanation'])+'## Source\n\n['+p['title']+']('+p['paper']+')\n'
 (ROOT/'content/explanations').mkdir(exist_ok=True)
 (ROOT/'content/explanations'/f'{s}.md').write_text(md)
 script='# '+p['short']+' — video narration and storyboard\n\nProduction draft. Approximately 2 minutes with diagram pauses.\n\nPaper: '+p['paper']+'\n\n'+''.join('## '+time+'\n\n**On screen:** '+visual+'\n\n**Narration:** '+narration+'\n\n' for time,visual,narration in a['scenes'])+'## Recording notes\n\n- Keep toy diagrams visibly labeled as illustrative.\n- Show paper figure/table identifiers when discussing measured results.\n- End with the project URL and a link to the primary paper.\n- Record narration, then add figures and captions; no recorded video is included in this draft.\n'
 (ROOT/'video-scripts'/f'{s}.md').write_text(script)
 save('resources/'+s+'-video-script.md',script)
 # Structured metadata contains only publicly sourced bibliographic facts.
 schema={'@context':'https://schema.org','@type':'ScholarlyArticle','name':p['title'],'author':[{'@type':'Person','name':n} for n in p['authors']],'url':p['paper'],'datePublished':str(p['year'])}
 f=D/'papers'/s/'index.html';v=f.read_text();f.write_text(v.replace('</head>','<script type="application/ld+json">'+json.dumps(schema).replace('<','\\u003c')+'</script></head>'))
paths=['']+['papers/'+p['slug']+'/' for p in PAPERS]+['videos/'+p['slug']+'/' for p in PAPERS]
if ORIGIN:
 save('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+e(ORIGIN+'/'+path)+'</loc><lastmod>2026-10-08</lastmod></url>' for path in paths)+'</urlset>')
 save('robots.txt','User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n')
save('404.html',head('Page not found | Liuyuan Jiang','Return to the research collection.')+'<main id="main" class="wrap" style="padding:70px 0"><h1>Page not found</h1><p><a href="/">Return to the research collection</a></p></main>'+footer())
