A=json.loads((ROOT/'content/articles.json').read_text())
BY={p['slug']:p for p in PAPERS}
def paragraphs(xs): return ''.join('<p>'+e(x)+'</p>' for x in xs)
def svgframe(label): return f'<svg viewBox="0 0 620 300" role="img" aria-label="{e(label)}"><g data-plot></g></svg>'
def demo(p):
 t=p['type'];s=p['slug']
 if t=='surf':
  return '<div class="demo" data-demo="surf"><h3>Try equal weights and equal distances</h3><p class="note">Exact scalarization of the toy objectives f₁(z) = z² and f₂(z) = (1 − z)⁴ for 0 ≤ z ≤ 1. Both objectives are minimized. The green points invert a numerically constructed arc-length map.</p><div class="demo-controls"><label for="sample-count">Number of solutions</label><input id="sample-count" type="range" min="4" max="24" value="10"><output for="sample-count" data-count>10</output></div>'+svgframe('Toy Pareto front comparing equal-weight and equal-arc-length points')+'<div class="legend"><span>Uniform weights</span><span>Uniform arc length</span></div><p class="metric" data-metric aria-live="polite"></p><p class="note">Gap CV is the standard deviation of adjacent arc-length gaps divided by their mean. Lower is more even. This calculated toy example illustrates geometry; it is not the paper’s experimental data or a run of its iterative SURF algorithm.</p></div>'
 if t=='constraint':
  return '<div class="demo" data-demo="constraint"><h3>Move the follower’s feasible boundary</h3><p>Minimize (y − 2x)² over 0 ≤ y ≤ x.</p><div class="demo-controls"><label for="outer-x">Outer decision x</label><input id="outer-x" type="range" min="0" max="3" step="0.05" value="1"><output for="outer-x" data-count>1.00</output></div>'+svgframe('Toy lower-level quadratic objective with a moving feasibility bound')+'<p class="metric" data-metric aria-live="polite"></p><p class="note">The unconstrained minimizer is 2x. For x ≥ 0, the feasible minimizer is y* = x. This is an exact toy lower-level solve, not an implementation of BLOCC.</p></div>'
 if t=='timing':
  return '<div class="demo" data-demo="timing"><h3>Same exposure, different timing</h3><p>Toggle whether a toy agent is long or flat before each interval. Returns are fixed at −20, +15, −10, +25, −15, and +5 basis points.</p><div class="toy-actions">'+''.join(f'<button type="button" data-action="{i}" aria-pressed="{str(i%2==0).lower()}">Interval {i+1}: {"Long" if i%2==0 else "Flat"}</button>' for i in range(6))+'</div><div class="demo-controls"><button class="button" type="button" data-invert>Invert schedule</button><button class="button" type="button" data-reset>Reset</button></div>'+svgframe('Synthetic interval returns and a selected binary exposure schedule')+'<p class="metric" data-metric aria-live="polite"></p><p class="note">Computed using the paper’s timing formula on six synthetic returns. This is not a trading simulation or empirical RetailAgent result. Inverting a schedule negates its centered timing score.</p></div>'
 if t=='speech':
  return '<div class="demo" data-demo="speech"><h3>Follow the two target sources</h3><div class="demo-controls"><button class="button primary" type="button" data-source="anchor" aria-pressed="true">Raw-input anchor</button><button class="button" type="button" data-source="enhanced" aria-pressed="false">Enhanced target</button></div><div class="diagram-flow"><div class="flow-node" data-node="input">Audio features<small>Observed input</small></div><span class="flow-separator" aria-hidden="true">›</span><div class="flow-node" data-node="repr">Intermediate features<small>Inside the speech model</small></div><span class="flow-separator" aria-hidden="true">›</span><div class="flow-node" data-node="quant">Random quantizer<small>Discrete pseudo-labels</small></div></div><p data-explanation aria-live="polite"></p><p class="note">Schematic target-source inspection. The buttons select which branch to explain; they do not change a training parameter.</p><h3>Measured downstream WER</h3>'+svgframe('Reported LibriSpeech word error rates for BEST-RQ and BiRQ')+'<div class="legend"><span>BEST-RQ</span><span>BiRQ</span></div><p class="note">Source: Table 2. 155M Conformer, 960h LibriSpeech SSL pretraining, 100h labeled fine-tuning. Lower WER is better.</p></div>'
 if t=='curvature':
  return '<div class="demo" data-demo="curvature"><h3>Joint curvature and reduced curvature</h3><p>Take Hγ(x, y) = x²/2 + γ(y − x)². Minimizing over y gives Fγ(x) = x²/2.</p><div class="demo-controls"><label for="penalty">Penalty γ</label><input id="penalty" type="range" min="1" max="30" value="5"><output for="penalty" data-count>5</output></div>'+svgframe('Toy joint-objective slice and penalty-independent reduced objective')+'<div class="legend"><span>Fixed slice Hγ(x, 0)</span><span>Reduced Fγ(x)</span></div><p class="metric" data-metric aria-live="polite"></p><p class="note">The fixed slice has curvature 1 + 2γ, while the reduced objective has curvature 1. This exact quadratic example illustrates the difference between objectives; it is not the theorem proof or measured convergence data.</p></div>'
 return '<div class="demo" data-demo="schedule"><h3>Inspect the update schedule</h3><div class="demo-controls"><button class="button primary" type="button" data-mode="single" aria-pressed="true">Single-loop illustration</button><button class="button" type="button" data-mode="nested" aria-pressed="false">Nested-loop illustration</button><button class="button" type="button" data-next>Next update</button></div><div class="diagram-flow"><div class="flow-node" data-stage="lower">Lower-level update<small data-lower>0 updates</small></div><span class="flow-separator" aria-hidden="true">›</span><div class="flow-node" data-stage="upper">Upper-level update<small data-upper>0 updates</small></div></div><p data-explanation aria-live="polite"></p><p class="note">The nested schedule uses four illustrative inner updates per outer step. The single-loop schedule uses one. These counts explain the layout of a loop and are not algorithm settings or runtime measurements from the paper. Coupled-constraint PBGD-Free retains an inner loop.</p></div>'
def bib(p):
 authors=' and '.join(p['authors']);key='jiang'+str(p['year'])+p['slug'].replace('-','')
 if p['slug']=='retailagent':key='zhang2026retailagent'
 if p['venue']=='Preprint':
  return f'@misc{{{key},\n  title = {{{p["title"]}}},\n  author = {{{authors}}},\n  year = {{{p["year"]}}},\n  eprint = {{{p["arxiv"]}}},\n  archivePrefix = {{arXiv}},\n  url = {{{p["paper"]}}}\n}}'
 return f'@inproceedings{{{key},\n  title = {{{p["title"]}}},\n  author = {{{authors}}},\n  booktitle = {{{p["venue"]}}},\n  year = {{{p["year"]}}},\n  url = {{{p["paper"]}}}\n}}'
def sourcehtml(p):
 return '<ul class="source-list">'+''.join('<li><a href="'+e(s['url'])+'">'+e(s['label'])+'</a></li>' for s in p['sources'])+'</ul>'
def videohtml(p,a):
 return '<p class="note">Production draft · approximately 2 minutes with diagram pauses · narration and storyboard, ready to record.</p>'+''.join(f'<div class="story-scene"><time>{e(time)}</time><p>{e(narration)}</p><p class="visual"><strong>On screen:</strong> {e(visual)}</p></div>' for time,visual,narration in a['scenes'])+f'<p><a class="button" href="../../resources/{p["slug"]}-video-script.md" download>Download narration and storyboard</a></p>'
def relatedhtml(p,a):
 return '<div class="pill-links">'+''.join(f'<a href="../{s}/">{e(BY[s]["short"])}</a>' for s in a['related'])+'</div>'
for p in PAPERS:
 s=p['slug'];a=A[s]
 labels=[('takeaway','The takeaway'),('idea','Explanation'),('interactive','Explore'),('evidence','Evidence'),('technical','Technical details'),('video','Video storyboard'),('citation','Cite this work')]
 toc='<aside class="toc" aria-label="Page contents">'+''.join(f'<a href="#{i}">{l}</a>' for i,l in labels)+'</aside>'
 actions=f'<a class="button primary" href="{p["paper"]}">Read the paper</a>'
 if p.get('code'):actions+=f'<a class="button" href="{p["code"]}">Code</a>'
 actions+='<a class="button" href="#video">Video storyboard</a>'
 evidence=''.join(f'<div class="evidence"><strong>{e(title)}</strong><p>{e(body)}</p><a href="{p["paper"]}">Source: primary paper</a></div>' for title,body in a['evidence'])
 explanation='<p>'+e(a['lead'])+'</p>'+''.join('<h3>'+e(title)+'</h3><p>'+e(text)+'</p>' for title,text in a['explanation'])
 venue_note=f'<p class="note">{e(p["venue_note"])}</p>' if p.get('venue_note') else ''
 body=head(p['short']+' | Liuyuan Jiang',p['description'],2,'papers/'+s+'/')+f'<main id="main" class="wrap"><header class="project-hero"><a class="route-back" href="../../index.html#papers">All research</a><div class="meta" style="margin-top:25px"><span class="venue">{e(p["venue"])}</span><span>{p["year"]}</span><span>{e(p["topic"])}</span></div><h1>{e(p["title"])}</h1><p class="subtitle">{e(p["question"])}</p><p class="authors">{e(", ".join(p["authors"]))}</p>{venue_note}<div class="actions">{actions}</div></header><div class="project-layout">{toc}<article class="article"><div id="takeaway" class="takeaway"><div class="eyebrow" style="margin-bottom:12px">The takeaway</div><p>{e(a["takeaway"])}</p></div><section id="idea"><h2>The problem and the idea</h2>{explanation}</section><section id="interactive"><h2>Explore the idea</h2>{demo(p)}</section><section id="evidence"><h2>What the paper reports</h2>{evidence}<p class="note">{e(a["boundary"])}</p></section><section id="technical"><h2>A closer look</h2><div class="equation">{e(a["formula"])}</div><p>{e(a["formula_note"])}</p><details><summary>Read the technical scope</summary><p>{e(a["formal"])}</p><a href="{p["paper"]}">Definitions, assumptions, and results in the paper</a></details><h3>Continue reading</h3>{relatedhtml(p,a)}</section><section id="video"><h2>Video storyboard</h2>{videohtml(p,a)}</section><section id="citation"><h2>Cite this work</h2><button class="button" type="button" data-copy="bibtex">Copy BibTeX</button><p class="status" role="status"></p><pre id="bibtex">{e(bib(p))}</pre><h3>Sources</h3>{sourcehtml(p)}</section></article></div></main>'+footer(2)
 save('papers/'+s+'/index.html',body)
 # Preserve old incoming URLs while keeping one substantive page per paper.
 target=f'../../papers/{s}/#idea'
 canonical=ORIGIN+'/papers/'+s+'/'
 redirect='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="This explanation is integrated into the paper project page."><meta name="robots" content="noindex,follow"><title>'+e(p['short'])+' explanation</title><link rel="canonical" href="'+e(canonical)+'"><meta http-equiv="refresh" content="0; url='+e(target)+'"></head><body><main><h1>Continue to the project page</h1><p><a href="'+e(target)+'">Read the integrated explanation</a></p></main><script>location.replace('+json.dumps(target)+');</script></body></html>'
 save('blog/'+s+'/index.html',redirect)
 md='# '+a['explanation_title']+'\n\n'+a['lead']+'\n\n'+''.join('## '+title+'\n\n'+text+'\n\n' for title,text in a['explanation'])+'## Source\n\n['+p['title']+']('+p['paper']+')\n'
 (ROOT/'content/explanations').mkdir(exist_ok=True)
 (ROOT/'content/explanations'/f'{s}.md').write_text(md)
 script='# '+p['short']+' — video narration and storyboard\n\nProduction draft. Approximately 2 minutes with diagram pauses.\n\nPaper: '+p['paper']+'\n\n'+''.join('## '+time+'\n\n**On screen:** '+visual+'\n\n**Narration:** '+narration+'\n\n' for time,visual,narration in a['scenes'])+'## Recording notes\n\n- Keep toy diagrams visibly labeled as illustrative.\n- Show paper figure/table identifiers when discussing measured results.\n- End with the project URL and a link to the primary paper.\n- Record narration, then add figures and captions; no recorded video is included in this draft.\n'
 (ROOT/'video-scripts'/f'{s}.md').write_text(script)
 save('resources/'+s+'-video-script.md',script)
 # Structured metadata contains only publicly sourced bibliographic facts.
 schema={'@context':'https://schema.org','@type':'ScholarlyArticle','name':p['title'],'author':[{'@type':'Person','name':n} for n in p['authors']],'url':p['paper'],'datePublished':str(p['year'])}
 f=D/'papers'/s/'index.html';v=f.read_text();f.write_text(v.replace('</head>','<script type="application/ld+json">'+json.dumps(schema).replace('<','\\u003c')+'</script></head>'))
paths=['']+['papers/'+p['slug']+'/' for p in PAPERS]
if ORIGIN:
 save('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+e(ORIGIN+'/'+path)+'</loc><lastmod>2026-10-08</lastmod></url>' for path in paths)+'</urlset>')
 save('robots.txt','User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n')
save('404.html',head('Page not found | Liuyuan Jiang','Return to the research collection.')+'<main id="main" class="wrap" style="padding:70px 0"><h1>Page not found</h1><p><a href="/">Return to the research collection</a></p></main>'+footer())
